#+title: Gnome Settings
* Keyboard Layout
Input source settings can be mamaged using =gsettings= tool. use the =get=
subcommand to query the keyboard layouts set in your session.
#+name: get-keyboard-input-sources
#+begin_src shell :results drawer
gsettings get org.gnome.desktop.input-sources sources
#+end_src

For a complete list of available keyboard layouts, query the =man 7
xkeyboard-config= page.

#+name: set-keyboard-input-sources
#+begin_src shell
gsettings \
    set org.gnome.desktop.input-sources \
    sources "[('xkb', 'us+alt-intl'), ('xkb', 'us'), ('xkb', 'latam')]"
#+end_src

See the [[https://wiki.debian.org/Keyboard#How_to_dynamically_manage_input_source_settings_from_the_command_line_.28modern_strategy.29][Debian Wiki]] for more details.

* Nordic GTK Themes
Download the packages from [[https://www.gnome-look.org/p/1267246/][gnome-look.org]], if you need more details look at the
project's [[https://github.com/EliverLara/Nordic][Github repository]].

#+begin_src shell
gsettings set org.gnome.desktop.interface gtk-theme "Nordic-darker-v40"
gsettings set org.gnome.desktop.wm.preferences theme "Nordic-darker-v40"
#+end_src

However, after doing this, some aplications like the file explorer might not
apply the new theme, this is caused aparently by lack of configuration for
GTK-4.

This can be solved (partially) by adding the style sheets inside [[file:gtk-4/][gtk-4]] folder
inside =$HOME/.config/= directory.
* Icons Themes
- [[https://www.gnome-look.org/p/1661983/][Colloid]]
- [[https://www.gnome-look.org/p/1533591/][Breeze]]

* Terminal
** Tab Bar Position
I like to display the tab bar at the bottom of the window

#+begin_src shell
gsettings set org.gnome.Terminal.Legacy.Settings tab-position bottom
#+end_src

** Theme
Apply the [[https://github.com/nordtheme/gnome-terminal][nord theme]] to the =gnome-terminal=

#+begin_src shell :dir ~/src
git clone https://github.com/nordtheme/gnome-terminal.git nord-gnome-terminal
#+end_src

After cloning the repository, run the =nord.sh= installer script.

#+begin_src shell :dir ~/src/nord-gnome-germinal/src
./nord.sh
#+end_src

This script will create a new =Nord= profile that you can set as your default.

** Font
If you don't like any of the available fonts, consider to install a [[file:nerdfonts.org::*How to install Nerd Fonts][Nerd Font]].

*** The GUI way
1. Click on the _hamburger_ menu of =gnome-terminal=
2. Click =Preferences= to open the "Preferences" dialog
3. From the side bar under the =Profiles= section select your profile (i.e. Nord)
4. Choose the =Text= tab
5. Check the =Text Appearance/Custom font= field, the "Choos A Terminal Font" will open
6. Pick the desired font, by scrolling or typing its name
7. When you find your font, click the =Select= button
8. Close the "Preferences" dialog

*** The programatic way
I took this idea from a [[https://ncona.com/2019/11/configuring-gnome-terminal-programmatically/][blog entry]]. I as it is show here doesn't work, but I
still interested in doing it this way. I will keep trying to make it work.

#+name: terminal-profile
#+begin_src shell
gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'
#+end_src

#+begin_src shell :var GNOME_TERMINAL_PROFILE=terminal-profile() :results raw
GSETTINGS_PATH=org.gnome.Terminal.Legacy.Profile:/org/terminal/legacy/profiles

gsettings set $GSETTINGS_PATH:/:$GNOME_TERMINAL_PROFILE/ use-system-font false
gsettings set $GSETTINGS_PATH:/:$GNOME_TERMINAL_PROFILE/ font 'Hasklug Nerd Font 12'
#+end_src
